version: "3.8"
services:
  uvr2mqtt:
    build: .
    image: henfri/uvr2mqtt:latest
    container_name: uvr2mqtt
    restart: unless-stopped
    volumes:
      - ${DOCKERCONFIG}/uvr/config.json:/app/config.json:ro
      - ${DOCKERCONFIG}/uvr/Neu.xml:/app/Neu.xml:ro
    working_dir: /app
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks: {}
